apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: nginx
  labels:
    app: hello-world
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:alpine 
        ports:
        - containerPort: 8080 
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf 
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config