apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: nginx
spec:
  selector:
    app: hello-world 
  ports:
  - port: 80 
    targetPort: 8080 
    nodePort: 30080
  type: LoadBalancer
